version: '3.8'

services:

  nginx:
    image: nginx
    restart: always
    environment:
      TZ: Asia/Tokyo
    ports:
      - 8080:80
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/log:/var/log/nginx
    links:
      - fluentd

  fluentd:
    build: ./fluentd
    restart: always
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - ./nginx/log:/var/log/nginx
    links:
      - elasticsearch
    ports:
      - 24224:24224
      - 24224:24224/udp

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.3
    restart: always
    environment:
      ES_JAVA_OPTS: -Xmx256m -Xms256m
      discovery.type: single-node
      xpack.security.enabled: false
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:8.1.3
    restart: always
    links:
      - elasticsearch
    ports:
      - 5601:5601
